server:
  port: 1016

datasource:
  driverName: mysql
  host: 127.0.0.1
  port: 3306
  database: godb
  username: root
  password: 123456
  charset: utf8

filesavepath:
  path: C:/Users/Arete/Desktop/filepath